version: "3.1"

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/config:/docker-entrypoint-initb.d
      - ./db/files:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - network


  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge